### ISSUE TITLE
Mouse ssues in overlay menu

### ISSUE THREAD

**Issue by SnakeyHips** [Kaldaien/FAR#38] opened 2017-05-02 21:21 UTC
Updating to 5.6.1 completely messes up the mouse for me when trying to select options in the overlay menu. I've got the game running in bordered mode @1080p and my native res is 1440p.

Also, pressing the "exit" button for the menu in the top right hand corner causes my USB 360 controller to continuously vibrate. If only I had a gf who could make use of this feature.

**Comment by Kaldaien** [comment] 2017-05-02 22:05
I can't reproduce this, but it would help if you closed the menu the right way.

A gamepad should close it by pressing Back + Start. Closing the config menu with a mouse is not suggested.

**Comment by SnakeyHips** [comment] 2017-05-02 22:33
It works fine on 5.6 so I'll just stay with that as maybe it's just some weird issue my end. Thanks for the reply and top work so far!

**Comment by Kaldaien** [comment] 2017-05-02 22:52
Oh, wait. I misread what you stated.

No, you cannot use the menu with a mouse if you use a resolution override in windowed mode like that. It's suggested that you use keyboard or gamepad. The game's coordinate space is different from the dimensions of the window and mouse input won't work correctly unless you have both things in agreement.

**Comment by Kaldaien** [comment] 2017-05-02 23:39
Pfft, I know what the problem is now; especially now that I know you're using windowed mode.

It's related to attempted fixes for ReShade's broken mouse processing. I broke my own in the process :-\

Attached is an alternate build of 0.5.6.2. Can you let me know if this fixes it for you?
[dxgi.zip](https://github.com/Kaldaien/FAR/files/972208/dxgi.zip)

**Comment by SnakeyHips** [comment] 2017-05-03 07:50
Yup that fixes it! Thanks!

**Closed** 2017-05-03 15:54 UTC
